# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ChangeFilenName.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(890, 595)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/1.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hl_tools = QtWidgets.QHBoxLayout()
        self.hl_tools.setObjectName("hl_tools")
        self.pushButton_src = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_src.setFont(font)
        self.pushButton_src.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_src.setObjectName("pushButton_src")
        self.hl_tools.addWidget(self.pushButton_src)
        self.pushButton_flush = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_flush.setFont(font)
        self.pushButton_flush.setObjectName("pushButton_flush")
        self.hl_tools.addWidget(self.pushButton_flush)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_tools.addItem(spacerItem)
        self.pushButton_dec = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_dec.setFont(font)
        self.pushButton_dec.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_dec.setObjectName("pushButton_dec")
        self.hl_tools.addWidget(self.pushButton_dec)
        self.pushButton_go = QtWidgets.QPushButton(Form)
        self.pushButton_go.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(12)
        self.pushButton_go.setFont(font)
        self.pushButton_go.setAutoFillBackground(False)
        self.pushButton_go.setObjectName("pushButton_go")
        self.hl_tools.addWidget(self.pushButton_go)
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setIconSize(QtCore.QSize(30, 30))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.hl_tools.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.hl_tools)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_path_src = QtWidgets.QLabel(Form)
        self.label_path_src.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_path_src.setFont(font)
        self.label_path_src.setObjectName("label_path_src")
        self.horizontalLayout.addWidget(self.label_path_src)
        self.label_path_dec = QtWidgets.QLabel(Form)
        self.label_path_dec.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_path_dec.setFont(font)
        self.label_path_dec.setObjectName("label_path_dec")
        self.horizontalLayout.addWidget(self.label_path_dec)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.hl_edits = QtWidgets.QHBoxLayout()
        self.hl_edits.setObjectName("hl_edits")
        self.lineEdit_mask = QtWidgets.QLineEdit(Form)
        self.lineEdit_mask.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_mask.setFont(font)
        self.lineEdit_mask.setPlaceholderText("")
        self.lineEdit_mask.setObjectName("lineEdit_mask")
        self.hl_edits.addWidget(self.lineEdit_mask)
        self.lineEdit_fake = QtWidgets.QLineEdit(Form)
        self.lineEdit_fake.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_fake.setFont(font)
        self.lineEdit_fake.setPlaceholderText("")
        self.lineEdit_fake.setObjectName("lineEdit_fake")
        self.hl_edits.addWidget(self.lineEdit_fake)
        self.verticalLayout.addLayout(self.hl_edits)
        self.hl_lists = QtWidgets.QHBoxLayout()
        self.hl_lists.setObjectName("hl_lists")
        self.listWidget_src_files = QtWidgets.QListWidget(Form)
        self.listWidget_src_files.setObjectName("listWidget_src_files")
        self.hl_lists.addWidget(self.listWidget_src_files)
        self.listWidget_dec_files = QtWidgets.QListWidget(Form)
        self.listWidget_dec_files.setObjectName("listWidget_dec_files")
        self.hl_lists.addWidget(self.listWidget_dec_files)
        self.verticalLayout.addLayout(self.hl_lists)
        self.retranslateUi(Form)
        self.pushButton_src.clicked.connect(lambda: Form.slot_clicked(self.pushButton_src))
        self.pushButton_dec.clicked.connect(lambda: Form.slot_clicked(self.pushButton_dec))
        self.checkBox.clicked.connect(Form.slot_covered)
        self.pushButton_go.clicked.connect(lambda: Form.slot_clicked(self.pushButton_go))
        self.lineEdit_mask.textChanged.connect(lambda: Form.slot_text_changed(self.lineEdit_mask))
        self.lineEdit_fake.textChanged.connect(lambda: Form.slot_text_changed(self.lineEdit_fake))
        self.pushButton_flush.clicked.connect(lambda: Form.slot_clicked(self.pushButton_flush))
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "批量修改文件名"))
        self.pushButton_src.setText(_translate("Form", "打开源文件夹"))
        self.pushButton_flush.setText(_translate("Form", "更新"))
        self.pushButton_dec.setText(_translate("Form", "指定保存文件夹"))
        self.pushButton_go.setText(_translate("Form", "Go"))
        self.checkBox.setText(_translate("Form", "覆盖"))
        self.label_path_src.setText(_translate("Form", "源文件路径："))
        self.label_path_dec.setText(_translate("Form", "保存路径："))
