# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_photo_exif.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1378, 823)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.vl_photo = QtWidgets.QVBoxLayout()
        self.vl_photo.setObjectName("vl_photo")
        self.wg_photo = QtWidgets.QWidget(self.centralwidget)
        self.wg_photo.setMinimumSize(QtCore.QSize(1052, 650))
        self.wg_photo.setMaximumSize(QtCore.QSize(1052, 650))
        self.wg_photo.setObjectName("wg_photo")
        self.vl_photo.addWidget(self.wg_photo)
        self.wg_exif = QtWidgets.QWidget(self.centralwidget)
        self.wg_exif.setMinimumSize(QtCore.QSize(1052, 0))
        self.wg_exif.setMaximumSize(QtCore.QSize(1052, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.wg_exif.setFont(font)
        self.wg_exif.setObjectName("wg_exif")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.wg_exif)
        self.verticalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb_camera = QtWidgets.QLabel(self.wg_exif)
        self.lb_camera.setObjectName("lb_camera")
        self.horizontalLayout_2.addWidget(self.lb_camera)
        self.lb_model = QtWidgets.QLabel(self.wg_exif)
        self.lb_model.setObjectName("lb_model")
        self.horizontalLayout_2.addWidget(self.lb_model)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb_weight = QtWidgets.QLabel(self.wg_exif)
        self.lb_weight.setObjectName("lb_weight")
        self.horizontalLayout_3.addWidget(self.lb_weight)
        self.lb_photo_size = QtWidgets.QLabel(self.wg_exif)
        self.lb_photo_size.setObjectName("lb_photo_size")
        self.horizontalLayout_3.addWidget(self.lb_photo_size)
        self.lb_resolution = QtWidgets.QLabel(self.wg_exif)
        self.lb_resolution.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_resolution.setObjectName("lb_resolution")
        self.horizontalLayout_3.addWidget(self.lb_resolution)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lb_photo_time = QtWidgets.QLabel(self.wg_exif)
        self.lb_photo_time.setObjectName("lb_photo_time")
        self.horizontalLayout_4.addWidget(self.lb_photo_time)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.vl_photo.addWidget(self.wg_exif)
        self.horizontalLayout_5.addLayout(self.vl_photo)
        self.frame_bench = QtWidgets.QFrame(self.centralwidget)
        self.frame_bench.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_bench.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_bench.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bench.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bench.setObjectName("frame_bench")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_bench)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tree_view = QtWidgets.QTreeView(self.frame_bench)
        self.tree_view.setMinimumSize(QtCore.QSize(0, 0))
        self.tree_view.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tree_view.setObjectName("tree_view")
        self.verticalLayout.addWidget(self.tree_view)
        self.list_wg = QtWidgets.QListWidget(self.frame_bench)
        self.list_wg.setObjectName("list_wg")
        self.verticalLayout.addWidget(self.list_wg)
        self.wg_nav = QtWidgets.QWidget(self.frame_bench)
        self.wg_nav.setMinimumSize(QtCore.QSize(300, 0))
        self.wg_nav.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(11)
        self.wg_nav.setFont(font)
        self.wg_nav.setObjectName("wg_nav")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wg_nav)
        self.horizontalLayout.setContentsMargins(0, 0, 2, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pb_prev = QtWidgets.QPushButton(self.wg_nav)
        self.pb_prev.setObjectName("pb_prev")
        self.verticalLayout_3.addWidget(self.pb_prev)
        self.pb_next = QtWidgets.QPushButton(self.wg_nav)
        self.pb_next.setObjectName("pb_next")
        self.verticalLayout_3.addWidget(self.pb_next)
        self.cb_auto_show = QtWidgets.QCheckBox(self.wg_nav)
        self.cb_auto_show.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cb_auto_show.setObjectName("cb_auto_show")
        self.verticalLayout_3.addWidget(self.cb_auto_show)
        self.cb_sub_dir = QtWidgets.QCheckBox(self.wg_nav)
        self.cb_sub_dir.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cb_sub_dir.setObjectName("cb_sub_dir")
        self.verticalLayout_3.addWidget(self.cb_sub_dir)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.vl_tools = QtWidgets.QVBoxLayout()
        self.vl_tools.setObjectName("vl_tools")
        self.dial = QtWidgets.QDial(self.wg_nav)
        self.dial.setMinimumSize(QtCore.QSize(90, 90))
        self.dial.setMaximumSize(QtCore.QSize(90, 90))
        self.dial.setObjectName("dial")
        self.vl_tools.addWidget(self.dial)
        self.horizontalLayout.addLayout(self.vl_tools)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pb_max_show = QtWidgets.QPushButton(self.wg_nav)
        self.pb_max_show.setObjectName("pb_max_show")
        self.verticalLayout_2.addWidget(self.pb_max_show)
        self.pushButton = QtWidgets.QPushButton(self.wg_nav)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.wg_nav)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.wg_nav)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.wg_nav)
        self.horizontalLayout_5.addWidget(self.frame_bench)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_search = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/images/search.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_search.setIcon(icon)
        self.action_search.setObjectName("action_search")
        self.action_select_all = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/images/select.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_select_all.setIcon(icon1)
        self.action_select_all.setObjectName("action_select_all")
        self.toolBar.addAction(self.action_search)
        self.toolBar.addAction(self.action_select_all)

        self.retranslateUi(MainWindow)
        self.pb_prev.clicked.connect(MainWindow._slot_btn_clicked)
        self.pb_next.clicked.connect(MainWindow._slot_btn_clicked)
        self.pb_max_show.clicked.connect(MainWindow._slot_btn_clicked)
        self.tree_view.clicked['QModelIndex'].connect(MainWindow._slot_tree_clicked)
        self.pushButton.clicked.connect(MainWindow._slot_btn_clicked)
        self.pushButton_2.clicked.connect(MainWindow._slot_btn_clicked)
        self.pushButton_3.clicked.connect(MainWindow._slot_btn_clicked)
        self.cb_auto_show.stateChanged['int'].connect(MainWindow._slot_check_changed)
        self.cb_sub_dir.stateChanged['int'].connect(MainWindow._slot_check_changed)
        self.toolBar.actionTriggered['QAction*'].connect(MainWindow._slot_action_triggered)
        self.list_wg.itemClicked['QListWidgetItem*'].connect(MainWindow._slot_list_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "照片分类排序"))
        self.lb_camera.setText(_translate("MainWindow", "相机厂商"))
        self.lb_model.setText(_translate("MainWindow", "相机型号"))
        self.lb_weight.setText(_translate("MainWindow", "相片大小"))
        self.lb_photo_size.setText(_translate("MainWindow", "相片尺寸"))
        self.lb_resolution.setText(_translate("MainWindow", "分辨率单位"))
        self.lb_photo_time.setText(_translate("MainWindow", "拍摄时间"))
        self.pb_prev.setText(_translate("MainWindow", "向前"))
        self.pb_next.setText(_translate("MainWindow", "向后"))
        self.cb_auto_show.setText(_translate("MainWindow", "自动播放"))
        self.cb_sub_dir.setText(_translate("MainWindow", "含子目录"))
        self.pb_max_show.setText(_translate("MainWindow", "放大"))
        self.pushButton.setText(_translate("MainWindow", "旋转"))
        self.pushButton_2.setText(_translate("MainWindow", "艺术"))
        self.pushButton_3.setText(_translate("MainWindow", "浮雕"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_search.setText(_translate("MainWindow", "搜索"))
        self.action_search.setToolTip(_translate("MainWindow", "在当前目录下搜索"))
        self.action_select_all.setText(_translate("MainWindow", "全选"))
        self.action_select_all.setToolTip(_translate("MainWindow", "选择所有内容"))
