# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_word2pdf.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1155, 682)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.label_src = QtWidgets.QLabel(self.centralwidget)
        self.label_src.setObjectName("label_src")
        self.horizontalLayout.addWidget(self.label_src)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listWidget_src = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_src.setObjectName("listWidget_src")
        self.verticalLayout.addWidget(self.listWidget_src)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_dst = QtWidgets.QLabel(self.centralwidget)
        self.label_dst.setObjectName("label_dst")
        self.horizontalLayout_2.addWidget(self.label_dst)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.listWidget_dst = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_dst.setObjectName("listWidget_dst")
        self.verticalLayout_2.addWidget(self.listWidget_dst)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1155, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpenSrc = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/images/open.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenSrc.setIcon(icon)
        self.actionOpenSrc.setObjectName("actionOpenSrc")
        self.actionOpenDst = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/images/save.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("res/dst3.gif"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOpenDst.setIcon(icon1)
        self.actionOpenDst.setObjectName("actionOpenDst")
        self.actionDoc2Pdf = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res/images/convert.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDoc2Pdf.setIcon(icon2)
        self.actionDoc2Pdf.setObjectName("actionDoc2Pdf")
        self.actionMergeDoc = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("res/images/merge.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMergeDoc.setIcon(icon3)
        self.actionMergeDoc.setObjectName("actionMergeDoc")
        self.actionpdf = QtWidgets.QAction(MainWindow)
        self.actionpdf.setObjectName("actionpdf")
        self.action_pdf = QtWidgets.QAction(MainWindow)
        self.action_pdf.setObjectName("action_pdf")
        self.actionFlush = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("res/images/flush.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFlush.setIcon(icon4)
        self.actionFlush.setObjectName("actionFlush")
        self.actionSetting = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("res/images/setting.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSetting.setIcon(icon5)
        self.actionSetting.setObjectName("actionSetting")
        self.actionword = QtWidgets.QAction(MainWindow)
        self.actionword.setObjectName("actionword")
        self.actionWaterMark = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("res/images/watermark.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWaterMark.setIcon(icon6)
        self.actionWaterMark.setObjectName("actionWaterMark")
        self.toolBar.addAction(self.actionOpenSrc)
        self.toolBar.addAction(self.actionFlush)
        self.toolBar.addAction(self.actionOpenDst)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDoc2Pdf)
        self.toolBar.addAction(self.actionMergeDoc)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionWaterMark)
        self.toolBar.addAction(self.actionSetting)
        self.menu.addAction(self.actionDoc2Pdf)
        self.menu.addAction(self.action_pdf)
        self.menu_2.addAction(self.actionMergeDoc)
        self.menu_2.addAction(self.actionpdf)
        self.menu_3.addAction(self.actionword)
        self.menu_3.addAction(self.actionSetting)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBar.actionTriggered['QAction*'].connect(MainWindow.slot_tools)
        self.checkBox.clicked['bool'].connect(MainWindow.slot_checked)
        self.listWidget_src.itemSelectionChanged.connect(MainWindow.slot_selected)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "文档处理"))
        self.checkBox.setText(_translate("MainWindow", "全选"))
        self.label_src.setText(_translate("MainWindow", "源目录："))
        self.label_dst.setText(_translate("MainWindow", "目标目录："))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menu.setTitle(_translate("MainWindow", "格式转换"))
        self.menu_2.setTitle(_translate("MainWindow", "文件合并"))
        self.menu_3.setTitle(_translate("MainWindow", "设置"))
        self.actionOpenSrc.setText(_translate("MainWindow", "打开"))
        self.actionOpenSrc.setToolTip(_translate("MainWindow", "指定源文件目录"))
        self.actionOpenDst.setText(_translate("MainWindow", "保存"))
        self.actionOpenDst.setToolTip(_translate("MainWindow", "指定保存目录"))
        self.actionDoc2Pdf.setText(_translate("MainWindow", "word 转 pdf"))
        self.actionDoc2Pdf.setToolTip(_translate("MainWindow", "word 转 pdf"))
        self.actionMergeDoc.setText(_translate("MainWindow", "word 文件合并"))
        self.actionMergeDoc.setToolTip(_translate("MainWindow", "word 文件合并"))
        self.actionpdf.setText(_translate("MainWindow", "pdf 文件合并"))
        self.action_pdf.setText(_translate("MainWindow", "图片 转 pdf"))
        self.actionFlush.setText(_translate("MainWindow", "刷新"))
        self.actionFlush.setToolTip(_translate("MainWindow", "更新源文件"))
        self.actionSetting.setText(_translate("MainWindow", "设置"))
        self.actionSetting.setToolTip(_translate("MainWindow", "设置"))
        self.actionword.setText(_translate("MainWindow", "word 文件设置"))
        self.actionWaterMark.setText(_translate("MainWindow", "水印"))
        self.actionWaterMark.setToolTip(_translate("MainWindow", "处理水印"))
